// Import the createSlice function from Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

// Create the authSlice slice using createSlice
export const authSlice = createSlice({
  name: "auth", // Slice name
  initialState: {
    isAuthenticated: false, // Initial authentication status
    user: {}, // Initial user data
  },
  reducers: {
    // Reducer function for setting the user and authentication status
    setUser: (state, { payload }) => {
      state.user = payload.user; // Set the user data from the payload
      state.isAuthenticated = true; // Set isAuthenticated to true
    },
    // Reducer function for logging out
    logout: (state) => {
      state.user = {}; // Clear the user data
      state.isAuthenticated = false; // Set isAuthenticated to false
    },
  },
});

// Export the action creators generated by createSlice
export const { setUser, logout } = authSlice.actions;

// Export the reducer function generated by createSlice
export default authSlice.reducer;
