// Import the configureStore function from Redux Toolkit
import { configureStore } from "@reduxjs/toolkit";

// Import the authReducer generated by the authSlice
import authReducer from "./auth.js";

// Configure and export the Redux store
export default configureStore({
  reducer: {
    auth: authReducer, // Combine reducers, 'auth' key in the store corresponds to authReducer
  },
});
